### ISSUE TITLE
Create Auth Component

### ISSUE THREAD

**Issue by arinze19** [arinze19/bookmark-ER-v2#2]
- Create basic auth component with `email`, `name`, `password` fields. 
- Up to you to decide if this should route to a `/auth` page or be a modal
- Ref: [selfish-twentys](https://selfish-twentys.netlify.app/auth)

**Comment by heisdeku** [comment]
Also it wasn't up to be to decide it to be a modal or route to "/auth" as the design has made it a modal bro.

Had fun doing it as a modal though, even though i had broken somethings
